version: 0.2
env:
  variables:
    REPOSITORY_NAME: test
phases:
  install:
    runtime-version:
      python: 3.9
    commands:
      - echo "Installing dependencies and running tests..."
      - echo Logging in to Amazon ECR...
      - apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
      - rm -rf /etc/apt/source.list.d/sbt.list
      - apt-get update -y
      - python --version
      - pip install --upgrade pip
      - pip install awscli --upgrade
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - REPOSITORY_URI=535002855046.dkr.ecr.us-east-1.amazonaws.com/cicdpipeline
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "ECR URI:$REPOSITORY_URI"
      - echo "Tag:$IMAGE_TAG"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Entered the build phase...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Creating imagedefinitions.json..."
      - echo "[{\"name\":\"MyContainer\",\"imageUri\":\"$REPOSITORY_URI:$IMAGE_TAG\"}]" > imagedefinitions.json
      - echo "Creating appspec.yaml..."
      - |
        cat <<EOF > appspec.yaml
        version: 1
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: "arn:aws:ecs:us-east-1:535002855046:task-definition/cicdpipeline-taskdef:42"
                LoadBalancerInfo:
                  ContainerName: "MyContainer"
                  ContainerPort: 80
        EOF
      - echo "Writing TaskDefinitionTemplatePath.json..."
      - |
        cat <<EOF > TaskDefinitionTemplatePath.json
        {
          "family": "cicdpipeline-taskdef",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "256",
          "memory": "512",
          "executionRoleArn": "arn:aws:iam::535002855046:role/ecspipeline",
          "containerDefinitions": [
            {
              "name": "MyContainer",
              "image": "$REPOSITORY_URI:$IMAGE_TAG",
              "essential": true,
              "portMappings": [
                {
                  "containerPort": 80,
                  "protocol": "tcp"
                }
              ],
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "/ecs/cicdpipeline",
                  "awslogs-region": "us-east-1",
                  "awslogs-stream-prefix": "ecs"
                }
              }
            }
          ]
        }
        EOF
      - echo "Listing all files:"
      - ls -alh
artifacts:
  files:
    - appspec.yaml
    - imagedefinitions.json
    - TaskDefinitionTemplatePath.json
