version: 0.2

env:
  variables:
    REPOSITORY_NAME: test
    TASK_DEFINITION_FILE: "task-definition.json"  # Consistent naming

phases:
  install:
    runtime-versions:  # Fixed syntax (plural)
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
      - rm -rf /etc/apt/sources.list.d/sbt.list  # Fixed typo (source -> sources)
      - apt-get update -y
      - python --version
      - pip install --upgrade pip
      - pip install awscli --upgrade

  pre_build:
    commands:
      - echo "Getting ECR details..."
      - REPOSITORY_URI="535002855046.dkr.ecr.us-east-1.amazonaws.com/cicdpipeline"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Building Docker images..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker images..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      # Generate imagedefinitions.json (properly saved to file)
      - echo "[{\"name\":\"MyContainer\",\"imageUri\":\"$REPOSITORY_URI:$IMAGE_TAG\"}]" > imagedefinitions.json
      
      # Generate updated task definition with current image tag
      - sed "s|:latest|:$IMAGE_TAG|g" taskdef.json > $TASK_DEFINITION_FILE
      
      # Generate appspec.yaml
      - cat <<EOF > appspec.yaml
        version: 1
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: "InfraStackMyTaskDef93E1369E"
                LoadBalancerInfo:
                  ContainerName: "MyContainer"
                  ContainerPort: 80
        EOF
      
      # Verify files
      - echo "Generated files:"
      - ls -la
      - echo "Task definition contents:"
      - cat $TASK_DEFINITION_FILE

artifacts:
  files:
    - appspec.yaml
    - imagedefinitions.json
    - task-definition.json  # Must match TASK_DEFINITION_FILE
  discard-paths: yes 
