version: 0.2

env:
  variables:
    REPOSITORY_NAME: "cicdpipeline"
    CONTAINER_NAME: "MyContainer"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y jq
      - pip install --upgrade pip
      - pip install awscli

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION="us-east-1"
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to ECR $REPOSITORY_URI
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo Registering new ECS task definition...
      - TASK_DEF=$(aws ecs describe-task-definition --task-definition InfraStackMyTaskDef93E1369E)
      - NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$REPOSITORY_URI:$IMAGE_TAG" '.taskDefinition | del(.status, .taskDefinitionArn, .revision, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) | .containerDefinitions[0].image = $IMAGE')
      - echo "$NEW_TASK_DEF" > new-task-def.json
      - TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --query "taskDefinition.taskDefinitionArn" --output text)
      - echo "New Task Definition ARN: $TASK_DEF_ARN"

      - echo Creating imagedefinitions.json for CodeDeploy...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

      - echo Writing appspec.yaml...
      - cat <<'EOF' > appspec.yaml
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "$TASK_DEF_ARN"
        LoadBalancerInfo:
          ContainerName: "$CONTAINER_NAME"
          ContainerPort: 80
EOF

artifacts:
  files:
    - appspec.yaml
    - imagedefinitions.json
